kvm: arm64: Include kvm_emulate.h in kvm/arm_psci.h
community inclusion
category: feature
bugzilla: https://gitee.com/openeuler/kernel/issues/IBY08N
Reference: https://lore.kernel.org/kvm/20250416134208.383984-1-steven.price@arm.com/T/

--------------------------------

Fix a potential build error (like below, when asm/kvm_emulate.h gets
included after the kvm/arm_psci.h) by including the missing header file
in kvm/arm_psci.h:

./include/kvm/arm_psci.h: In function ‘kvm_psci_version’:
./include/kvm/arm_psci.h:29:13: error: implicit declaration of function
   ‘vcpu_has_feature’; did you mean ‘cpu_have_feature’? [-Werror=implicit-function-declaration]
   29 |         if (vcpu_has_feature(vcpu, KVM_ARM_VCPU_PSCI_0_2)) {
	         |             ^~~~~~~~~~~~~~~~
			       |             cpu_have_feature

Signed-off-by: Suzuki K Poulose <suzuki.poulose@arm.com>
Signed-off-by: Steven Price <steven.price@arm.com>
Signed-off-by: Yiwei Zhuang <zhuangyiwei@huawei.com>
Signed-off-by: Xu Raoqing <xuraoqing@huawei.com>