execve: fix sysctl_max_arg_strlen undefined error for external modules
External modules (e.g., Lustre ptlrpc_gss) that include <linux/binfmts.h>
fail at MODPOST with:
  ERROR: "sysctl_max_arg_strlen" [.../ptlrpc_gss.ko] undefined!

This is because commit 75962fb89f09 ("execve: gcc argument list space
enlargement") redefined MAX_ARG_STRLEN as the runtime variable
sysctl_max_arg_strlen, which is not exported to modules.

Fix this by guarding the redefinition with #ifdef MODULE, so that
external modules see the original compile-time constant
ORIG_MAX_ARG_STRLEN while vmlinux code continues to use the sysctl
tunable. This avoids the need for EXPORT_SYMBOL and is semantically
correct since modules do not participate in the execve path.

Fixes: 2b30a9cf8d0c ("execve: gcc argument list space enlargement")
Signed-off-by: Yongliang Gao <leonylgao@tencent.com>
Reviewed-by: Jianping Liu <frankjpliu@tencent.com>