proc/stat: fix compile when using allyesconfig
Fix compile error when .config created from "make allyesconfig".
The error log as below:
fs/proc/bt_stat.c: In function ‘__show_stat’:
fs/proc/bt_stat.c:169:17: error: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘long unsigned int’ [-Werror=format=]
  169 |                 "\nctxt %llu\n"
      |                 ^~~~~~~~~~~~~~~
......
  177 |                 nr_forks(),
      |                 ~~~~~~~~~~
      |                 |
      |                 long unsigned int
fs/proc/bt_stat.c:171:29: note: format string is defined here
  171 |                 "processes %d\n"
      |                            ~^
      |                             |
      |                             int
      |                            %ld
  CC      fs/ext4/extents.o
  CC      fs/reiserfs/fix_node.o
cc1: all warnings being treated as errors
make[4]: *** [scripts/Makefile.build:243: fs/proc/bt_stat.o] Error 1

Fixes: c8564c6bb241 ("proc: fix the display error of the processes field in /proc/stat")
Signed-off-by: Jianping Liu <frankjpliu@tencent.com>
Reviewed-by: Yongliang Gao <leonylgao@tencent.com>