i2c: zhaoxin: make the local helpers static
zxi2c_fifo_irq_xfer() and zxi2c_xfer() are only used inside
drivers/i2c/busses/i2c-zhaoxin.c and are not declared in any header, so
a W=1 build fails:

  drivers/i2c/busses/i2c-zhaoxin.c:175:5: error: no previous prototype
  for 'zxi2c_fifo_irq_xfer' [-Werror=missing-prototypes]
  drivers/i2c/busses/i2c-zhaoxin.c:313:5: error: no previous prototype
  for 'zxi2c_xfer' [-Werror=missing-prototypes]

Make both static.

Signed-off-by: Yue Wang <1939455790@qq.com>