loongarch_iommu: fix compile error
Fix compile error as below:
/kernel-6.6.119-46/drivers/iommu/loongarch_iommu.c:1205:10: error: 'const struct iommu_ops' has no member named 'set_platform_dma_ops'
 1205 |         .set_platform_dma_ops = la_domain_set_plaform_dma_ops,
      |          ^~~~~~~~~~~~~~~~~~~~
/kernel-6.6.119-46/drivers/iommu/loongarch_iommu.c:1205:33: error: initialization of 'struct iommu_domain *' from incompatible pointer type 'void (*)(struct device *)' [-Werror=incompatible-pointer-types]
 1205 |         .set_platform_dma_ops = la_domain_set_plaform_dma_ops,
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~/kernel-6.6.119-46/drivers/iommu/loongarch_iommu.c:1205:33: note: (near initialization for 'la_iommu_ops.identity_domain')
  CC [M]  sound/pci/echoaudio/indigoiox.o
/kernel-6.6.119-46/drivers/iommu/loongarch_iommu.c:1786:19: warning: 'la_iommu_setup' defined but not used [-Wunused-function] 1786 | static int __init la_iommu_setup(char *str)
      |                   ^~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[4]: *** [/kernel-6.6.119-46/scripts/Makefile.build:243: drivers/iommu/loongarch_iommu.o] Error 1
make[3]: *** [/kernel-6.6.119-46/scripts/Makefile.build:480: drivers/iommu] Error 2

The compile error is cause by OCK PR590:
[Upstream commit 24b1d476167df3e30c7a53b67765bf3c787c5160]

Signed-off-by: Jianping Liu <frankjpliu@tencent.com>