crypto: x86/sm3-zhaoxin - make the local helpers static
sm3_generic_block_fn(), zx_sm3_update() and zx_sm3_finup() are only
used inside arch/x86/crypto/sm3-zhaoxin-gmi.c and are not declared in
any header, so a W=1 build fails:

  arch/x86/crypto/sm3-zhaoxin-gmi.c:61:6: error: no previous prototype
  for 'sm3_generic_block_fn' [-Werror=missing-prototypes]
  arch/x86/crypto/sm3-zhaoxin-gmi.c:140:5: error: no previous prototype
  for 'zx_sm3_update' [-Werror=missing-prototypes]
  arch/x86/crypto/sm3-zhaoxin-gmi.c:153:5: error: no previous prototype
  for 'zx_sm3_finup' [-Werror=missing-prototypes]

Make all three static.

Signed-off-by: Yue Wang <1939455790@qq.com>