tkernel: shield_mounts: make shield_mounts_release() static
shield_mounts_release() is only referenced by the proc_ops table in the
same file, but it is defined without the static qualifier and is not
declared in any header. A W=1 build with
CONFIG_TKERNEL_SHIELD_MOUNTS=y therefore fails:

  kernel/tkernel/shield_mounts.c:260:5: error: no previous prototype
  for 'shield_mounts_release' [-Werror=missing-prototypes]

Make the function static.

Signed-off-by: Yue Wang <1939455790@qq.com>