kernel/sysctl: fix ld error when using notk.config
When using the config which generated by "make tencentconfig notkconfig",
there will ld error as below:
ld: kernel/sysctl.o:(.data+0x1e8): undefined reference to `sysctl_memcg_async'
ld: kernel/sysctl.o:(.data+0x200): undefined reference to `memcg_async_sysctl_handler'

The error is caused by:
sysctl_memcg_async and memcg_async_sysctl_handler is in
kernel/tkernel/memcg_async/memcg_async.c, which will be compiled only when
CONFIG_TKERNEL is enabled.

Signed-off-by: Jianping Liu <frankjpliu@tencent.com>
Reviewed-by: Yongliang Gao <leonylgao@tencent.com>