mm: oom: fix gfp_allows_early_oom() visibility for make defconfig build
Previously gfp_allows_early_oom() was defined inside CONFIG_MEMCG,
causing a build error when make defconfig build:
  mm/oom_kill.c: error: implicit declaration of function 'gfp_allows_early_oom'

Signed-off-by: Huang Cun <cunhuang@tencent.com>