Revert "dist: fix BuildRequires for mlnx commercial-grade driver"
This reverts commit 58b079bec6985d8ff4759dba4a72742f7a8ea146.
Which cause build error on x86_64 as below:
Error: One or more required packages for installing OFED-internal are missing.
Please install the missing packages using your Linux distribution Package Management tool.
Run:
yum install kernel-srpm-macros

Signed-off-by: Jianping Liu <frankjpliu@tencent.com>
Reviewed-by: Yongliang Gao <leonylgao@tencent.com>